sudo: false
language: java
jdk:
  - oraclejdk8

env:
  global:
   - secure: "ajolnwNwvlqK331ebEaewpABT8855U4p4uRyXnm3/od3WtJgTD6EpQXBCJWsaHoIQs5U9TDZGoM+bT4h4XJu0bbPj2TQpF6oZX42MUqjmzEiDPeXvuUqhGiSllP9VINL8w7G2R1NbN02xWnxF3n5rHluZcYVrb7OGjLUqwTjzVeDXlm5tDiqQhEAb8LwXEBptHBTsau+lAsAFZ7rm9FaL9fxtXRs22U9bSur+w6KVWLZqlgX6GBfh52p0sueqLv3FQ9yt0fFsNJSRmS460ZRHhowXGutrpvGUWaDzNQQJvlk+jwvSxhWqluibhxGvRm6a1iMG4rHvT39jCNpF2fjTJpLIQYuigZIDHKTUV7UZ5adI6RmTH7D8nW9GY+Q12x3Bv3JBQ8LFYqk9KLh2cleK71fIvpRLjybd86fsBcoRLxdBltf3Vcx4AuazqGyrbH3pzpLQ8iRIT8tLxTkYG8+cmdLgrv+v98H5QUPikzyNXysRtP53rijDk9tSPiO9hKOSm7EattX65u3pmdAFU6oMxWHl7mHHaI1cMgWLx55aYXCGkQFqFVhYDvv/GWT+tIroow1raPND6jmG/HrE/kBnSqIrIaiflbxjPp3YsybttkqoacRFPyKNlA0eN8hB2B5na7V8mggMDGMgiiPBSo6cofksJFLfuZaUGJrKy9YY6Y="
   - secure: "ZGyFs/3Mh9FPwbcBLNR6qNCZt+u33af1HNoTpc4eS2Efb4vw3aGYp9vQfB+HLHMJC2wZVarCx4gfujtNdd2nHLes3SoLLtW9RsVnv9exRowzWuLL6z/kvsHVlIodPZrJhpKiSge8ZjFWyZ/2dknuOJbT0LAfTnmAsEzyvnh6ur9Ag+mnZ+nVc8ADHomSnlg+O7AxUnxlVI/Wby/9wHRxkNPcT36C1KO8uNqL93UPeefbCxhfcNJ13UvOyJ1whhsPa36Mzuz5O7sqTfS7UJemqb4ZD5vaRLE+/FZosbm5T4usRr9vydXPdXt2spR0yJDuP5fULK91x3DFP6GyK8Ll5fr7MCJcRT9lP8ql0Ttwqu4SWAHDDz0U0L3cA3Yl6A4sYD/Cl06/RC/0HcBfjCIQCUo+dTvd2jNkNRQAszd7EPOnZbxoXT8tWjCTV0GdhKhrKKn+SRHgAC18wKuAiCGy5XGz3Pzk/ViK7QGLnKM4DPgShchwa+Hv/VAy1Kz5brg7F3oZpx3DFfhES73nI83Jd5iioD9TiD8UoalUwWI8EuVAOwi5UgwJqIzm55XbXV09kcaAE4n6q9DXVNyv8MngdL5KiHwHtVKKAGg636JdSMO3OoEzs7DHzEo1Z/ULECwLIHOn5AxAyQkFNSuDjJdFyG2e+caBeG7tThcjGTpxWiQ="

before_install: "git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling"

deploy:
  provider: script
  script: "mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml"
  skip_cleanup: true
  on:
    tags: false
